name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: unit tests for .Net Core
        uses: deadmann/AdvancedRestHandler@latest
        with:
          project_path: Tests/AdvancedRestHandler.Test_NetCore
          report_name: advanced_rest_handler_dotnet_core_test
          report_title: Advanced Rest Handler - Test .Net Core
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: advanced_rest_handler_dotnet_core_test.md
          gist_badge_label: 'Advanced Rest Handler .Net Core: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
